### ISSUE TITLE
[QUESTION] Where does the custom code & plugins fit into the picture

### ISSUE THREAD

**Issue by SinghDivneet** [aws-samples/magento-ecs-cdk#10]
#### Please describe your question here

As I understand this init script would be installing any sample data what I wanted to understand how & where to integrate the custom code instead of the sample data? 

How much time does it take to install said sample data & for each container to start? 

Is this setup tested for production/UAT setups? 

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by allamand** [comment]
Hi @SinghDivneet, thanks for your interest.

In this example, we provide simble bash scripts that will be executed at pod startup : https://github.com/aws-samples/magento-ecs-cdk/blob/main/docker/scripts/post-init/01-install-sample-data.sh#L53 in this we install the magento sample datas. You can choose to customize thoses scripts to install your own website. You can also build your own image docker with your installation and used it as base image for the deployment : https://github.com/aws-samples/magento-ecs-cdk/blob/main/docker/Dockerfile#L1

In this project we have separated a uniq magento admin Task, which will be used to bootstrap the environment and execute installations scripts, or upgrades scripts, and MagentoService which will serve requests, but will wait for the Admin task to finished it's job.

If you rely on the uses of Shared file system we have monitor thoses installation times to install the magento sample datas for the 1rst time:
- ~= 20min on FsX
- ~= 50mn on EFS

The goal of this project is to propose a viable production architecture for magento, but you should take your own tests depending on your own configuration/needs.
