### ISSUE TITLE
The runtime parameter of nodejs14.x is no longer supporte

### ISSUE THREAD

**Issue by MinhHungPhan** [aws-samples/magento-ecs-cdk#32]
## Description

Output error:

```
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We
recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: a8defa90-54
35-456a-8852-e1187b5fe29d)" (RequestToken: f4e393f9-ae75-a198-84fd-abdc9869ccee, HandlerErrorCode: InvalidRequest)
```

I encountered an issue while running the `make deploy` command to deploy the Magento stack in my AWS account. The deployment failed due to the runtime parameter `nodejs14.x` no longer being supported for creating or updating AWS Lambda functions. The recommendation is to use the new runtime `nodejs20.x`.

Upon investigation, I checked the `package.json` file and found that it is currently using `@types/node": "^14"`.

**Comment by allamand** [comment]
Should be fixed now
